### ISSUE TITLE
Counting time for tasks when the application is not running

### ISSUE THREAD

**Issue by moon-mu** [Hoglet/TimeIT#12]
Currently for projects time tracking I am using Rachota. If task is running and rachota is closed the next time I start it it asks me if I want to add the time since my last software use to the coresponding task. The only problem for me is that I can have only one active countable task at single moment so I was looking for alternative with multiple tasks running. Thank you for your time!

**Comment by hackel** [comment]
Since I was indeed pinged on the other bug report, I thought I would mention that I would actually like to see this feature too.  I think it could work just like the idle timer does now.  If you start TimeIT and a timer was left in an open state, it should pop up a dialogue informing you that it has been x hours/minutes since you were last active, would you like to continue, stop/revert, stop/continue.

I've gotten in the habit of using TimeIT to punch-in/out, so that I can keep track of my in-office time in addition to time spent on individual projects, and so I still want it to record the time if I ever need to restart my computer, etc.
